# Generated by Django 5.2.6 on 2025-09-11 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='first/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('hd', 'hair-drier'), ('bm', 'bat-minton'), ('cl', 'cat-lead'), ('hm', 'hand-malt'), ('bc', 'base-candle'), ('lm', 'left-mount')], max_length=2)),
            ],
        ),
    ]
